// INTER STRUCTURE DYNAMIC

#define BLOCK_FLUID_K 00.0*TIME_SCALE*TIME_SCALE

// BLOCKS

#define BLOCK_SCALING 0.15
#define COLLISION_K_IN_BLOCK 300.0*TIME_SCALE*TIME_SCALE
#define COLLISION_C_IN_BLOCK 0.5*TIME_SCALE

#define HARD_BLOCK_MASS 5000.0 * BLOCK_SCALING * BLOCK_SCALING                                      // CHECK IF THIS SCALING IS CORRECT
#define HARD_BLOCK_HARDNESS 1000.0*TIME_SCALE*TIME_SCALE/HARD_BLOCK_DX/HARD_BLOCK_DY                /BLOCK_SCALING/BLOCK_SCALING
#define HARD_BLOCK_STEADYNESS 0.5*TIME_SCALE/HARD_BLOCK_DY/HARD_BLOCK_DX                            /BLOCK_SCALING/BLOCK_SCALING
#define HARD_BLOCK_WIDTH 5.0                                                                        *BLOCK_SCALING
#define HARD_BLOCK_HEIGHT 5.0                                                                       *BLOCK_SCALING
#define HARD_BLOCK_DX 1.0                                                                           *BLOCK_SCALING
#define HARD_BLOCK_DY 1.0                                                                           *BLOCK_SCALING
#define HARD_BLOCK_PARTICLE_COL_RADIUS 10.0*NODE_SHAPE_RADIUS/SPATIAL_SCALE                         *BLOCK_SCALING  
#define HARD_BLOCK_MAX_DIST_FACTOR_CONSTANT 20.0
#define HARD_BLOCK_CENTER_TOP MathUtils::Vector{BOUND_BOX_POS_X+BOUND_BOX_WIDTH/2-HARD_BLOCK_WIDTH/2, 0.0}
#define HARD_BLOCK_DATA HARD_BLOCK_MASS, HARD_BLOCK_HARDNESS, HARD_BLOCK_STEADYNESS, HARD_BLOCK_WIDTH, HARD_BLOCK_HEIGHT, HARD_BLOCK_DX, HARD_BLOCK_DY, HARD_BLOCK_PARTICLE_COL_RADIUS, HARD_BLOCK_MAX_DIST_FACTOR_CONSTANT
#define HARD_BLOCK HARD_BLOCK_DATA, HARD_BLOCK_CENTER_TOP

#define JELLO_BLOCK_MASS 1300.0 * BLOCK_SCALING * BLOCK_SCALING                                     // CHECK IF THIS SCALING IS CORRECT
#define JELLO_BLOCK_HARDNESS 10.0*TIME_SCALE*TIME_SCALE/JELLO_BLOCK_DX/JELLO_BLOCK_DY               /BLOCK_SCALING/BLOCK_SCALING
#define JELLO_BLOCK_STEADYNESS 0.001*TIME_SCALE/JELLO_BLOCK_DY/JELLO_BLOCK_DX                       /BLOCK_SCALING/BLOCK_SCALING
#define JELLO_BLOCK_WIDTH 5.0                                                                       *BLOCK_SCALING
#define JELLO_BLOCK_HEIGHT 5.0                                                                      *BLOCK_SCALING
#define JELLO_BLOCK_DX 0.5                                                                          *BLOCK_SCALING
#define JELLO_BLOCK_DY 0.5                                                                          *BLOCK_SCALING
#define JELLO_BLOCK_PARTICLE_COL_RADIUS 30.0*NODE_SHAPE_RADIUS/SPATIAL_SCALE                        *BLOCK_SCALING 
#define JELLO_BLOCK_MAX_DIST_FACTOR_CONSTANT 4.0
#define JELLO_BLOCK_CENTER_TOP MathUtils::Vector{BOUND_BOX_POS_X+BOUND_BOX_WIDTH/2-JELLO_BLOCK_WIDTH/2, 0.0}
#define JELLO_BLOCK_DATA JELLO_BLOCK_MASS, JELLO_BLOCK_HARDNESS, JELLO_BLOCK_STEADYNESS, JELLO_BLOCK_WIDTH, JELLO_BLOCK_HEIGHT, JELLO_BLOCK_DX, JELLO_BLOCK_DY, JELLO_BLOCK_PARTICLE_COL_RADIUS, JELLO_BLOCK_MAX_DIST_FACTOR_CONSTANT
#define JELLO_BLOCK JELLO_BLOCK_DATA, JELLO_BLOCK_CENTER_TOP

#define JELLYFISH_BLOCK_MASS 1000.0 * BLOCK_SCALING * BLOCK_SCALING                                 // CHECK IF THIS SCALING IS CORRECT
#define JELLYFISH_BLOCK_HARDNESS 2.5*TIME_SCALE*TIME_SCALE/JELLYFISH_BLOCK_DX/JELLYFISH_BLOCK_DY    /BLOCK_SCALING/BLOCK_SCALING
#define JELLYFISH_BLOCK_STEADYNESS 0.001*TIME_SCALE/JELLYFISH_BLOCK_DY/JELLYFISH_BLOCK_DX           /BLOCK_SCALING/BLOCK_SCALING
#define JELLYFISH_BLOCK_WIDTH 5.0                                                                   *BLOCK_SCALING
#define JELLYFISH_BLOCK_HEIGHT 5.0                                                                  *BLOCK_SCALING
#define JELLYFISH_BLOCK_DX 0.25                                                                     *BLOCK_SCALING
#define JELLYFISH_BLOCK_DY 0.25                                                                     *BLOCK_SCALING
#define JELLYFISH_BLOCK_PARTICLE_COL_RADIUS 50.0*NODE_SHAPE_RADIUS/SPATIAL_SCALE                    *BLOCK_SCALING
#define JELLYFISH_BLOCK_MAX_DIST_FACTOR_CONSTANT 20.0
#define JELLYFISH_BLOCK_CENTER_TOP MathUtils::Vector{BOUND_BOX_POS_X+BOUND_BOX_WIDTH/2-JELLYFISH_BLOCK_WIDTH/2, 0.0}
#define JELLYFISH_BLOCK_DATA JELLYFISH_BLOCK_MASS, JELLYFISH_BLOCK_HARDNESS, JELLYFISH_BLOCK_STEADYNESS, JELLYFISH_BLOCK_WIDTH, JELLYFISH_BLOCK_HEIGHT, JELLYFISH_BLOCK_DX, JELLYFISH_BLOCK_DY, JELLYFISH_BLOCK_PARTICLE_COL_RADIUS, JELLYFISH_BLOCK_MAX_DIST_FACTOR_CONSTANT
#define JELLYFISH_BLOCK JELLYFISH_BLOCK_DATA, JELLYFISH_BLOCK_CENTER_TOP

// FLUIDS

#define WATER_FLUID_DENSITY 1000.0
#define WATER_FLUID_DAMPING 1000/TIME_SCALE/TIME_SCALE*WATER_FLUID_DX*WATER_FLUID_DY // Fluid elasticity
#define WATER_FLUID_VISCOSITY 1*TIME_SCALE // Fluid viscosity
#define WATER_FLUID_WIDTH BOUND_BOX_WIDTH
#define WATER_FLUID_HEIGHT 5.0
#define WATER_FLUID_DX WATER_FLUID_PARTICLE_COL_RADIUS
#define WATER_FLUID_DY WATER_FLUID_PARTICLE_COL_RADIUS
#define WATER_FLUID_PARTICLE_COL_RADIUS 10.0*NODE_SHAPE_RADIUS/SPATIAL_SCALE
#define WATER_FLUID_FILL_BOT MathUtils::Vector{BOUND_BOX_POS_X+BOUND_BOX_WIDTH/2-WATER_FLUID_WIDTH/2, BOUND_BOX_POS_Y+BOUND_BOX_HEIGHT-WATER_FLUID_HEIGHT}
#define WATER_FLUID_DATA WATER_FLUID_DENSITY, WATER_FLUID_WIDTH, WATER_FLUID_HEIGHT, WATER_FLUID_PARTICLE_COL_RADIUS
#define WATER_FLUID WATER_FLUID_DATA, WATER_FLUID_FILL_BOT
#define WATER_BLOCK_VISC 10*WATER_FLUID_VISCOSITY
// TIP: lowering WATER_FLUID_DAMPING gives a more fluid like fluid, but the volume will be smaller, and the density won't be WATER_FLUID_DENSITY
// TIP: hight WATER_FLUID_VISCOSITY can have a goo like effect

#define OIL_FLUID_DENSITY 600.0
#define OIL_FLUID_DAMPING 1000/TIME_SCALE/TIME_SCALE*OIL_FLUID_DX*OIL_FLUID_DY // Fluid elasticity
#define OIL_FLUID_VISCOSITY 750*TIME_SCALE // Fluid viscosity
#define OIL_FLUID_WIDTH BOUND_BOX_WIDTH
#define OIL_FLUID_HEIGHT 1.0
#define OIL_FLUID_DX OIL_FLUID_PARTICLE_COL_RADIUS
#define OIL_FLUID_DY OIL_FLUID_PARTICLE_COL_RADIUS
#define OIL_FLUID_PARTICLE_COL_RADIUS 5.0*NODE_SHAPE_RADIUS/SPATIAL_SCALE
#define OIL_FLUID_FILL_BOT MathUtils::Vector{BOUND_BOX_POS_X+BOUND_BOX_WIDTH/2-OIL_FLUID_WIDTH/2, BOUND_BOX_POS_Y+BOUND_BOX_HEIGHT-OIL_FLUID_HEIGHT}
#define OIL_FLUID_DATA OIL_FLUID_DENSITY, OIL_FLUID_WIDTH, OIL_FLUID_HEIGHT, OIL_FLUID_PARTICLE_COL_RADIUS
#define OIL_FLUID OIL_FLUID_DATA, OIL_FLUID_FILL_BOT
#define OIL_BLOCK_VISC 0.05*OIL_FLUID_VISCOSITY